### ISSUE TITLE
Updating Regression Tests and Examples

### ISSUE THREAD

**Issue by jpmorgan98** [CEMeNT-PSAAP/MCDC#126]
The MPI issues keep failing out after repos are forked and we need to do better about testing all functionality. The specific tests we need to add:
- [x] Parallel regression test
- [x] Numba regression test
- [x] MPI & Numba Regression tests
- [x] Updating examples to have current functionality
I think as a stop gap measure we can write a number of SLURM or LSF batch scripts for Lassen or Quartz to at least somewhat optimize the process tho let me know what yall think.

**Comment by ilhamv** [comment]
Effort to address this: #131

**Comment by jpmorgan98** [comment]
I think we should retool the tests to not be so long. I will tackle this!

**Comment by ilhamv** [comment]
Also, note that now we do mpi test with mpiexec=2 and mpiexec=4. We can just do one of them.

**Comment by jpmorgan98** [comment]
Ya I think a github action only gives us 2 CPU cores anyways.

**Comment by spasmann** [comment]
Dang. 4 would be ideal for DD tests.

**Comment by jpmorgan98** [comment]
We can still launch 4 threads in that case they just wont be at all performant
