### ISSUE TITLE
Visualization merging

### ISSUE THREAD

**Issue by jpmorgan98** [CEMeNT-PSAAP/MCDC#138]
I am trying to merge the visualizer into main but am having some difficulties

**Comment by jpmorgan98** [comment]
# Background
@RohanPankaj added a visualization capabilities as a REU project over summer 2023. I am trying to merge it and recon with the alterations in MC/DC and with some of the new dependency.

In the current visualization is handled via [Netgen](https://ngsolve.org/) a full fat multiphyscis FEA solver that has x86 builds in [conda](https://anaconda.org/conda-forge/netgen). The problem is that Netgen currently requires a [manual build on ARM MacOS](https://docu.ngsolve.org/latest/install/installmacnative.html) and has no listed support for ppc64 (Power9). We don't need visualization as a strict requirement for MC/DC so I might make the configuration and testing of Netgen a non-standard option requiring additional flags to our current [install script](https://github.com/CEMeNT-PSAAP/MCDC/blob/main/install.sh)

## Next Steps 
- [ ] Handle merge between new MC/DC and old MC/DC
- [ ] Configure Netgen on my local machine validate visualizer with new MC/DC version
- [ ] Understanding Netgen as a dependency and install requirements

**Comment by spasmann** [comment]
Curious do we know if the other dependencies,`ngsolve `and `distinctipy`, have similar issues?

**Comment by jpmorgan98** [comment]
The dependencies have all been added and seem to be working on MAC and windows. I had to do some bug hunting to make sure all tests pass but as of PR #143 things seem to be working. When that PR is approved I will close this issue

**Comment by jpmorgan98** [comment]
ngsolve is a pip only command for osz-arm64 (M1/2/3)
