### ISSUE TITLE
Issue on Quartz: HYDU_sock_connect unable to connect

### ISSUE THREAD

**Issue by spasmann** [CEMeNT-PSAAP/MCDC#148]
Running into an issue on Quartz when I submit jobs from my PC (jobs run normally when submitting submitting from my Mac). All PC batch jobs fail with multiple errors like:
```
[proxy:0:23@quartz2664] HYDU_sock_connect (lib/utils/sock.c:140): unable to connect from "quartz2664" to "quartz79" (No route to host)
[proxy:0:23@quartz2664] main (proxy/pmip.c:105): unable to connect to server quartz79 at port 43377 (check for firewalls!)
srun: error: quartz2664: task 23: Exited with exit code 5
```

This is occurring regardless of branch or input deck. Based on similar bugs [here](https://github.com/pmodels/mpich/issues/1146) and [here](https://stackoverflow.com/questions/20018954/mpich2-on-multiple-machines-hydu-sock-connect-error) it seems to be an issue either with my ssh or hostname issue. 

I've submitted an LC-Hotline ticket and will report back what they say.

**Comment by jpmorgan98** [comment]
Are you sure you are using the MPI package from quartz and building off of that? Type `which mpirun`, `which mpiexec` and or `which srun`. Also check the module maybe? If you tell me exactly what to pull I can start trying out different versions/distributions of MPI

**Comment by spasmann** [comment]
Never heard back from LC-Hotline, but the  issue went away the next day. Closing the issue for now.
