### ISSUE TITLE
Resolving issues related to iQMC

### ISSUE THREAD

**Issue by ilhamv** [CEMeNT-PSAAP/MCDC#209]
We temporarily skip iQMC regression tests to achieve more concurrent developments in the same code base.

This Issue tracks the progress in resolving appearing issues.

The PR where the issue (partially failing some regression tests) started: #198

**Comment by jpmorgan98** [comment]
attempted fix #215

**Comment by ilhamv** [comment]
@sam, iQMC currently passes all the tests except `iqmc_kornreich_pi` in Numba mode.

**Comment by spasmann** [comment]
That's odd. Thanks for the heads up. I'll give this a look as soon as I can.

**Comment by ilhamv** [comment]
It is addressed in #223. This turns out to be a non-issue. It seems to be my local environment.
