### ISSUE TITLE
RNG unit test failure - TypeError

### ISSUE THREAD

**Issue by goodman17c** [CEMeNT-PSAAP/MCDC#60]
You Silly Goose.
The RNG unit test is failing with a Type Error.

Pytest failure error message attached below.
[YouSillyGoose.txt](https://github.com/CEMeNT-PSAAP/MCDC/files/10036999/YouSillyGoose.txt)

**Comment by ilhamv** [comment]
My bad! I was adding verification and regression tests, which required some reconfigurations, which seemed to break some of the unit test mechanics. Nevertheless, it's fixed now.
